"""Runtime bootstrap wrapper scripts for the Claude Code plugin bundle (WP05).

Generates the ``bin/spec-kitty-wrapper`` (bash) and ``bin/spec-kitty-wrapper.cmd``
(Windows CMD) scripts that Claude Code invokes when executing a Spec Kitty skill.

Both wrappers implement the same two-step runtime fallback:

1. If ``spec-kitty`` is on PATH, delegate directly (fast path for users who have
   the CLI installed).
2. If ``uvx`` is on PATH, run ``uvx spec-kitty-cli=={VERSION}`` (fallback for
   users who only have ``uv`` installed).
3. If neither is available, print a helpful error and exit 1.

``__SPEC_KITTY_VERSION__`` is substituted with the real version string at build
time by :func:`write_wrappers`.  The wrapper files are generated artefacts and
are **not** committed to the source repository — they live only under the
caller-supplied ``bundle_dir``.

**Scope guard (FR-016, C-006):** This module only writes to the
``bin/`` subdirectory of the caller-supplied ``bundle_dir``.  It never installs,
registers, enables, or publishes the bundle.
"""

from __future__ import annotations

import os
import stat
from pathlib import Path

from specify_cli.core.utils import ensure_within_directory

# Placeholder that is substituted at build time with the real package version.
_VERSION_PLACEHOLDER = "__SPEC_KITTY_VERSION__"

# Template for the bash wrapper script.
_BASH_WRAPPER_TEMPLATE = """\
#!/usr/bin/env bash
# Spec Kitty runtime bootstrap — PATH-check with uvx fallback.
# Generated by spec-kitty plugin build. Do not edit manually.
set -euo pipefail

VERSION="{version}"

if command -v spec-kitty >/dev/null 2>&1; then
    exec spec-kitty "$@"
fi

if command -v uvx >/dev/null 2>&1; then
    exec uvx "spec-kitty-cli==${{VERSION}}" "$@"
fi

echo "Error: spec-kitty is not installed and uvx is not available." >&2
echo "Install spec-kitty: pip install spec-kitty-cli" >&2
exit 1
"""

# Template for the Windows CMD wrapper script.
_CMD_WRAPPER_TEMPLATE = """\
@echo off
REM Spec Kitty runtime bootstrap for Windows.
REM Generated by spec-kitty plugin build. Do not edit manually.
SET VERSION={version}

where spec-kitty >nul 2>&1
IF NOT ERRORLEVEL 1 (
    spec-kitty %*
    EXIT /B %ERRORLEVEL%
)

where uvx >nul 2>&1
IF NOT ERRORLEVEL 1 (
    uvx spec-kitty-cli==%VERSION% %*
    EXIT /B %ERRORLEVEL%
)

echo Error: spec-kitty is not installed and uvx is not available.
echo Install spec-kitty: pip install spec-kitty-cli
EXIT /B 1
"""

# Owner-only rwx bits for a local executable file.
_EXECUTABLE_MODE = stat.S_IRUSR | stat.S_IWUSR | stat.S_IXUSR


def _write_owner_only_executable(path: Path, content: str) -> None:
    """Write *content* to *path* via a fresh owner-only executable temp file."""
    temp_path = path.parent / f".{path.name}.tmp"
    temp_path.unlink(missing_ok=True)
    fd = os.open(temp_path, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, _EXECUTABLE_MODE)
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="") as handle:
            handle.write(content)
        temp_path.replace(path)
    except Exception:
        temp_path.unlink(missing_ok=True)
        raise


def write_wrappers(bundle_dir: Path, version: str) -> None:
    """Write ``bin/spec-kitty-wrapper`` and ``bin/spec-kitty-wrapper.cmd``.

    Both files are generated under ``bundle_dir / "bin"`` with ``version``
    substituted for :data:`_VERSION_PLACEHOLDER`.  The bash script is made
    owner-executable (mode 700); Windows filesystem permissions are unchanged.

    Parameters
    ----------
    bundle_dir:
        Root of the plugin bundle (e.g. ``dist/spec-kitty-plugins/claude-code/``).
    version:
        The resolved package version string (e.g. ``"3.2.0"``).  Must be a
        non-empty string; the caller is responsible for validation.

    Raises
    ------
    ValueError
        When *version* is empty.
    """
    if not version:
        raise ValueError("version must be a non-empty string")

    bin_dir = bundle_dir / "bin"
    bin_dir.mkdir(parents=True, exist_ok=True)

    bash_path = ensure_within_directory(bin_dir / "spec-kitty-wrapper", bundle_dir)
    _write_owner_only_executable(
        bash_path,
        _BASH_WRAPPER_TEMPLATE.format(version=version),
    )

    cmd_path = ensure_within_directory(bin_dir / "spec-kitty-wrapper.cmd", bundle_dir)
    cmd_path.write_text(
        _CMD_WRAPPER_TEMPLATE.format(version=version),
        encoding="utf-8",
    )


def wrapper_bash_content(version: str) -> str:
    """Return the rendered bash wrapper content for *version*.

    Useful for inspection and testing without touching the filesystem.
    """
    return _BASH_WRAPPER_TEMPLATE.format(version=version)


def wrapper_cmd_content(version: str) -> str:
    """Return the rendered Windows CMD wrapper content for *version*.

    Useful for inspection and testing without touching the filesystem.
    """
    return _CMD_WRAPPER_TEMPLATE.format(version=version)


# NOTE: wrapper_bash_content / wrapper_cmd_content are public helpers consumed
# only by tests (filesystem-free inspection). They remain importable by name but
# are intentionally NOT in __all__ so the no-dead-symbols gate stays green.
__all__ = [
    "write_wrappers",
]
